### ISSUE TITLE
blockchain.tex suggestions

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/catapult-whitepaper#44]
- [x] page 36 “The maximum change rate of 5% per block makes it hard for an attacker with considerably less than 50% importance to create a better chain in secret.” -> Why 5% rate change makes it hard for an attacker to create a better chain?
 - [x] page 39 transfer transaction not referenced nor described before. You could add a footnote or reference to docs.
 - [x] page 39: effective amount formula format looks different than page 31 effectiveFee format (spaces, camel case,...)

**Comment by Jaguar0625** [comment]
> effective amount formula format looks different than page 31 effectiveFee

1. effective fee: the fee paid by sender to block harvester; dependent on block fee multiplier
1. effective amount: fee paid by sender to network (e.g. to register namespace); dependent on network dynamic fee multiplier 

so the two are intentionally different (unless this was comment about formatting)

**Comment by dgarcia360** [comment]
The comment was about formatting, see:

- \mathfunc{effectiveFee}(T) = \structField{B}{FeeMultiplier} \cdot \mathfunc{sizeof}(T)$$ --> variables written in camelCase
- \mathname{effective amount} = \: & \mathname{base amount} \cdot \mathname{dynamic fee multiplier} --> variables written in lowercase with spaces

**Comment by gimre-xymcity** [comment]
@dgarcia360 formatting is intentional, whenever actual fields or variables are described `mathfunc` (math fuction) or `structField` are used (FeeMultiplier is ofc actual field of a block)

whenever there's a text description in math mode - `mathname` is used

(in short: syntax implies semantic)
