### ISSUE TITLE
trees.tex suggestions

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/catapult-whitepaper#49]
For the hash function H mentioned in the paper, Symbol uses the 512-bit SHA3 hash function.

To calculate the transactionsRoot , H is used but seems to be 256-bit (32 bytes).

**Comment by Jaguar0625** [comment]
Assuming you're referring to the following from cryptography.tex:
> For the hash function $H$ mentioned in the paper, \codenamespace uses the 512-bit SHA3 hash function.

1. that is removed in 9.6.3 version
2. it doesn't apply to trees chapter since it is specifically referring to Bernstein2011 paper
