### ISSUE TITLE
network.tex suggestions

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/catapult-whitepaper#50]
- [x] “should contain a random subset of these nodes” Possible clarity needed, each one has an independent random subset that is determined when?
- [x] “API writers is experimental.” What if I don’t want experimental features in my application? Is there another alternative? Is it default disabled or enabled, or is it even possible to disable?
- [x] “individual writers can be checked out” Unclear what checked out means, as this is its first mention. Only a specific writer on a certain node? All of a certain writer type across the network?
- [x] pg 61 network:nodeEqualityStrategy settings are discussed without introducing what it’s for. The introduction does not come until the next page at the beginning of 12.6 Node Discovery.

**Comment by Jaguar0625** [comment]
> API writers is experimental

is dropped in 9.6.3 version of WP
