### ISSUE TITLE
Definition of "target" in blockchain.tex

### ISSUE THREAD

**Issue by ivyfung1** [nemtech/catapult-whitepaper#9]
**target: defines per-harvester power that increases the as time since last harvested block increases.**

The sentence seems to have missing words.

**Comment by Jaguar0625** [comment]
it should be either
1. defines per-harvester power that increases as time since last harvested block increases
2. defines per-harvester power that increases as the time since last harvested block increases

**Comment by Jaguar0625** [comment]
Fixed in 58b7355.
